Flask_Web_Core/Models/ErrorViewModel.cs
namespace Flask_Web_Core.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Flask_Web_Core/Models/UserDetails.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace Flask_Web_Core.Models
{
    public class UserDetails : IdentityUser
    {
        public string UserName { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string DupPassword { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }

        public int UserProfileID { get; set; } = 0;
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsEmailConfirmed { get; set; }
    }
}

Flask_Web_Core/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Flask_Web_Core.Controllers
{
    public class DashboardController : Controller
    {
        //[Authorize(Roles = "Admin, User, SomeRoleName")]
        public IActionResult Index()
        {
            if(User.Identity.IsAuthenticated || HttpContext.User.Identity.IsAuthenticated)
            {
                TempData["Success"] = "Login is sucessful";

               return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

Flask_Web_Core/Controllers/HomeController.cs
using Flask_Web_Core.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Flask_Web_Core.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Flask_Web_Core/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using System.Security.Claims;
using Flask_Web_Core.Models;
using System.Web;
//using Microsoft.AspNetCore.Server.HttpSys;
using Microsoft.AspNet.Identity;
using System.Net;
//using Microsoft.IdentityModel.Claims;

namespace Flask_Web_Core.Controllers
{
    public class LoginController : Controller
    {
        //var userData = HttpContext.User.Identity.Name.Split('.');
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if(HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoginAfter(UserDetails userDetails)
        {
            var claim = new Claim(userDetails.UserName, userDetails.Password);
            var identity = new ClaimsIdentity(new[] { claim }, "BasicAuthentication");
            var principal = new ClaimsPrincipal(identity);
            var props = new AuthenticationProperties();
            props.IsPersistent = userDetails.RememberMe;
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props);
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SignOff()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

        public JsonResult sendPassword(string emailID)
        {
            return Json(new string[] { });
        }

        public string CallAPI(string callMethod, string Body, Method method)
        {
            var client = new RestClient("http://192.168.0.1");
            var request = new RestRequest("api/item/", method);
            request.RequestFormat = DataFormat.Json;
            //request.AddBody(new  { ItemName = someName, Price = 19.99 });
            var response = client.ExecuteAsync(request);
            return string.Empty;
        }
    }
}

Flask_Web_Core/Controllers/SignUpController.cs
using Flask_Web_Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Flask_Web_Core.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(UserDetails usrDetails)
        {
            return View(usrDetails);
        }

        public JsonResult userExists(string emailID)
        {
            return Json(new string[] { });
        }
    }
}

Flask_Web_Core/Views/Dashboard/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Dashboard";
}
@if(User.Identity.IsAuthenticated)
{
    if(TempData["Success"] != null)
    {
        <h1 class="text-success" style="color:green;">@TempData["Success"]</h1>
    }
}

Flask_Web_Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Flask_Web_Core/Views/Login/ForgotPassword.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	Layout = null;
	ViewData["Title"] = "Option Strategies - Recover Password";
}
<!DOCTYPE html>
<html lang="en">
  <head>
	  <title>@ViewData["Title"]</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  
	  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	  <link rel="stylesheet" href="../css/style.css">
	  <style type="text/css">
		  .sreq
		  {
			  color:red;
		  }
		  .ftco-section {
			  padding: 3em 0;
		  }
	  </style>
  </head>
  <body>
	  <section class="ftco-section">
		  <div class="container">
			  <div class="row justify-content-center">
				  <div class="col-md-6 text-center mb-5">
					  <h2 class="heading-section">Implement Your Own Option Strategies</h2>
					  </div>
					  </div>
					  <div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="img" style="background-image: url(../images/bg-1.jpg);">
			      </div>
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h5 class="mb-4">Recover Password</h5>
			      		</div>
						  <div class="w-100">
							  <p class="social-media d-flex justify-content-end">
								  <a asp-action="Index" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-home"></span></a>
								  </p>
						  </div>
			      	</div>
					  <div class="signin-form">
						  <div class="form-group mb-3">
			      			<label class="label" for="name">Email</label>
			      			<input type="text" class="form-control" placeholder="Email" id="txtEmail" required>
							  <span id="errTxt" style="color:red;font-size:15px;"></span>
						  </div>
						  <div class="form-group">
							  <button type="button" class="form-control btn btn-primary rounded submit px-3" id="btnForgot">submit</button>
							  </div>
					  </div>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
	<script src="../js/jquery.min.js"></script>
	<script src="../js/popper.js"></script>
	<script src="../js/bootstrap.min.js"></script>
	<script src="../js/main.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			function isValidEmail(emailID) {
				var pattern = /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;
				return pattern.test(emailID);
			}
			$('#btnForgot').on('click', function(e){
				e.preventDefault();
				var email = $('#txtEmail').val();
				$('#errTxt').text('');
				if(email != ''){
					if (!isValidEmail(email)){
						$('#errTxt').text('Please enter valid email');
					}else {
						$.ajax({
							type : 'POST',
							async: false,
							url: 'sendPassword',
							dataType: "json",
							contentType: 'application/json; charset=utf-8',
							data : { 'emailID' : email},
							success: function(data) {
								$('#errTxt').text('Email has been sent. Please check inbox');
							},
							error: function() {
								alert("Error occured!!");
							}
						});
					}
				} else if (email == ""){
					$('#errTxt').text('Please enter email');
				}
			});
		});
	</script>
</body>
</html>

Flask_Web_Core/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Flask_Web_Core.Models.UserDetails;
@{
	Layout = null;
    ViewData["Title"] = "Option Strategies";
}
<!doctype html>
<html lang="en">
  <head>
  	<title>@ViewData["Title"]</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/style.css">
	<style type="text/css">
		  .sreq
		  {
			  color:red;
		  }
		  .ftco-section {
			  padding: 3em 0;
		  }
	  </style>
	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Implement Your Own Option Strategies</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="img" style="background-image: url(images/bg-1.jpg);">
			      </div>
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Sign In</h3>
			      		</div>
			      	</div>
					  <form asp-controller="Login" asp-action="LoginAfter" class="signin-form" method="post">
			      		<div class="form-group mb-3">
			      			<label class="label" for="name">Username</label>
			      			<input type="text" class="form-control" placeholder="Username" asp-for="UserName" required />
			      		</div>
		            <div class="form-group mb-3">
		            	<label class="label" for="password">Password</label>
		              <input asp-for ="Password" type="password" class="form-control" placeholder="Password" required />
		            </div>
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary rounded submit px-3" id="btnSubmit">Sign In</button>
		            </div>
		            <div class="form-group d-md-flex">
		            	<div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">Remember Me
									  <input asp-for ="RememberMe" type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div>
									<div class="w-50 text-md-right">
										<a asp-action="ForgotPassword">Forgot Password</a>
									</div>
		            </div>
		          </form>
		          <p class="text-center">Not a member? <a asp-action="Index" asp-controller="SignUp">Sign Up</a></p>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
	<script src="../js/jquery.min.js"></script>
	<script src="../js/popper.js"></script>
	<script src="../js/bootstrap.min.js"></script>
	<script src="../js/main.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			function isValidEmail(emailID) {
				var pattern = /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;
				return pattern.test(emailID);
			}
			$('#btnSubmit1').on('click', function(e){
				e.preventDefault();
			});
		});
	</script>
	</body>
</html>

Flask_Web_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Option Strategies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Flask_Web_Core.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Option Strategies</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <form asp-controller="Login" asp-action="SignOff" method="post" id="frmSignoff">
                            </form>
                            <a href ="#" class="nav-link text-dark" id="btnlogoff">Logout</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.ToString("YYYY")  - Option Strategies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(document).ready(function(){
            $('#btnlogoff').on('click', function(e){
                e.preventDefault();
                $('#frmSignoff').submit();
            });
        });
    </script>

</body>
</html>

Flask_Web_Core/Views/SignUp/Index.cshtml
@model Flask_Web_Core.Models.UserDetails;
@{
    Layout = null;
    ViewData["Title"] = "Option Strategies - Sign Up user";
}
<!DOCTYPE html>
<html lang="en">
  <head>
	  <title>@ViewData["Title"]</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  
	  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	  <link rel="stylesheet" href="../css/style.css">
	  <style type="text/css">
		  .sreq
		  {
			  color:red;
		  }
		  .ftco-section {
			  padding: 3em 0;
		  }
	  </style>
  </head>
  <body>
	  <section class="ftco-section">
		  <div class="container">
			  <div class="row justify-content-center">
				  <div class="col-md-6 text-center mb-5">
					  <h2 class="heading-section">Implement Your Own Option Strategies</h2>
					  </div>
					  </div>
					  <div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="img" style="background-image: url(../images/bg-1.jpg);">
			      </div>
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h5 class="mb-4">Sign Up</h5>
			      		</div>
						  <div class="w-100">
							  <p class="social-media d-flex justify-content-end">
								  <a asp-action="Index" asp-controller="Login" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-home"></span></a>
								  </p>
						  </div>
			      	</div>
					  <div class="signin-form">
						  <form asp-controller="SignUp" asp-action="Register" class="signin-form" method="post" id="formRegister">
							  <div class="form-group mb-3">
								  <label class="label" for="FirstName">First Name <span class="sreq">*</span></label>
								  <input type="text" class="form-control req" data-err="err_FirstName" placeholder="First Name" asp-for="FirstName" required />
								  <span id="err_FirstName" style="color:red;font-size:15px;"></span>
							  </div>
							  <div class="form-group mb-3">
								  <label class="label" for="LastName">Last Name <span class="sreq">*</span></label>
								  <input type="text" class="form-control req" data-err="err_LastName" placeholder="Last Name" asp-for="LastName" required />
								  <span id="err_LastName" style="color:red;font-size:15px;"></span>
							  </div>
							  <div class="form-group mb-3">
								  <label class="label" for="Email">Email <span class="sreq">*</span></label>
								  <input type="text" class="form-control req" placeholder="Email" data-err="err_Email"  asp-for="Email" id="Email" required />
								  <span id="err_Email" style="color:red;font-size:15px;"></span>
							  </div>
							  <div class="form-group mb-3">
								  <label class="label" for="Password">Password <span class="sreq">*</span></label>
								  <input type="password" class="form-control req" placeholder="Password" asp-for="Password" data-err="err_Password" id="Password" required />
								  <span id="err_Password" style="color:red;font-size:15px;"></span>
							  </div>
							  <div class="form-group mb-3">
								  <label class="label" for="DupPassword">Re-type Password <span class="sreq">*</span></label>
								  <input type="password" class="form-control req" placeholder="Re-type Password" asp-for="DupPassword" data-err="err_DupPassword" id="DupPassword" required />
								  <span id="err_DupPassword" style="color:red;font-size:15px;"></span>
							  </div>
							  <div class="form-group  mb-3">
							  <button type="button" class="form-control btn btn-primary rounded submit px-3" id="btnRegister">Register</button>
							  </div>
						  </form>
						  
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
	<script src="../js/jquery.min.js"></script>
	<script src="../js/popper.js"></script>
	<script src="../js/bootstrap.min.js"></script>
	<script src="../js/main.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			function isValidEmail(emailID) {
				var pattern = /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;
				return pattern.test(emailID);
			}
			function validEmail(){
				var $eml = $('#Email');
				var email = $eml.val();
				var etxtID = $eml.data('err');
				if($('#'+etxtID).text()!= '' || $('#'+etxtID).text()== 'Please enter valid email' || $('#'+etxtID).text()== 'Email exists. Please check.')
				$('#'+etxtID).text('');
				if(email != ''){
					if (!isValidEmail(email)){
						$('#'+etxtID).text('Please enter valid email');
						return false;
					}else {
						$.ajax({
							type : 'POST',
							async: false,
							url: 'userExists',
							dataType: "json",
							contentType: 'application/json; charset=utf-8',
							data : { 'emailID' : email},
							success: function(data) {
								$('#'+etxtID).text('Email exists. Please check.');
								return false;
							},
							error: function() {
								alert("Error occured!!");
								return false;
							}
						});
					}
				} else if (email == ""){
					$('#'+etxtID).text('Please enter email');
					return false;
				}
				return true;
			}
			function validPassword()
			{
				var pwd = $('#Password').val();
				var dupPwd = $('#DupPassword').val();
				if(pwd != '' && dupPwd != '' && pwd == dupPwd)
				return true;
				else
				return false;
			}
			$('#Password, #DupPassword').on('keydown focus focusout keyup keypress', function(){
				$('#err_DupPassword').text('');
				var validPWD = validPassword();
				if(!validPWD)
				$('#err_DupPassword').text('Please type exact password as above');
			});
			$('#btnRegister').on('click', function(e){
				e.preventDefault();
				$('.req').each(function(index){
					var $this = $(this);
					var errID = $this.data('err');
					$('#'+errID).text('');
					if($this.val() == '')
					{
						$('#'+errID).text( $this.attr('placeholder') + ' is required');
					}
				});
				var validEml = validEmail();
				var validPWD = validPassword();
				if(!validPWD)
				$('#err_DupPassword').text('Please type exact password as above');				
			});


			$('#btnForgot').on('click', function(e){
				e.preventDefault();
				var email = $('#txtEmail').val();
				$('#errTxt').text('');
				if(email != ''){
					if (!isValidEmail(email)){
						$('#errTxt').text('Please enter valid email');
					}else {
						$.ajax({
							type : 'POST',
							async: false,
							url: 'sendPassword',
							dataType: "json",
							contentType: 'application/json; charset=utf-8',
							data : { 'emailID' : email},
							success: function(data) {
								$('#errTxt').text('Email has been sent. Please check inbox');
							},
							error: function() {
								alert("Error occured!!");
							}
						});
					}
				} else if (email == ""){
					$('#errTxt').text('Please enter email');
				}
			});
		});
	</script>
</body>
</html>